version: '3.5'

services:
  dicomweb:
    build:
      context: .
      dockerfile: Dockerfile
    image: dicomweb-server:latest
    hostname: dicomweb-server
    ports:
      - '5985:5985' # DICOMWeb
    depends_on:
      - couchdb
    restart: unless-stopped
  
  ##
  # LINK: https://hub.docker.com/_/couchdb
  ##
  couchdb:
    image: couchdb:2.3.1
    hostname: couchdb
    volumes:
      - ./couchdb-data:/opt/couchdb/data
    ports:
      - '5984:5984'
    restart: unless-stopped